import random
import logging

try:
    import spacy
    nlp = spacy.load("en_core_web_md")
    HAS_SPACY = True
except (ImportError, OSError):
    HAS_SPACY = False
    logging.warning("SpaCy or 'en_core_web_md' not found. Pragmatic randomness via POS-dropping will fallback to a basic heuristic. To install: `pip install spacy && python -m spacy download en_core_web_md`")

def apply_pragmatic_randomness(text: str, drop_prob: float = 0.3) -> str:
    """
    Applies Pragmatic Randomness: Emulates the human tendency to omit certain parts of speech (POS)
    when context (the image) makes it obvious.
    
    For example:
    - Dropping the main noun: "Change the dress to striped" -> "Change to striped"
    - Dropping prepositions: "leather texture shoes made of" -> "leather texture shoes"
    
    Args:
        text (str): The text generated by VLM.
        drop_prob (float): The probability to trigger POS dropping.
        
    Returns:
        str: Text with a randomly dropped non-essential POS.
    """
    # Only apply dropping with given probability
    if random.random() > drop_prob:
        return text
        
    if not HAS_SPACY:
        # Fallback: simple string manipulation if spacy not available
        # Attempt to drop common prepositions ("of", "with", "the")
        words = text.split()
        stopwords = {"of", "with", "the", "a", "an", "this", "that"}
        filtered = [w for w in words if w.lower() not in stopwords]
        if len(filtered) < len(words) and len(filtered) > 1:
             return " ".join(filtered)
        return text

    doc = nlp(text)
    
    # Target POS to drop (those that don't entirely destroy the instruction intent)
    # NOUN: the user knows what the object is, so they might not say "the bag"
    # ADP / DET: "made of" -> "made", "the red" -> "red"
    target_pos = ["NOUN", "ADP", "DET"]
    
    # Extract tokens that match these POS
    droppable_tokens = [token for token in doc if token.pos_ in target_pos]
    
    if not droppable_tokens:
        return text
        
    # Pick a random token to drop
    token_to_drop = random.choice(droppable_tokens)
    
    # Reconstruct text without this token
    new_tokens = [t.text_with_ws for t in doc if t.i != token_to_drop.i]
    new_text = "".join(new_tokens).strip()

    # Clean up double spaces
    new_text = " ".join(new_text.split())
    
    return new_text

if __name__ == "__main__":
    # Test cases
    test_texts = [
        "Change the laptop to a black single version.",
        "Make it look like a studio photography shot.",
        "Make these shoes suitable for a formal evening gala.",
        "Change the dress, but no red colors please."
    ]
    
    print("Testing Pragmatic Randomness:")
    for t in test_texts:
        # Force probability to 1.0 for testing
        print(f"Original: {t}")
        print(f"Dropped:  {apply_pragmatic_randomness(t, drop_prob=1.0)}\n")
